### ISSUE TITLE
Fireball_Manager

### ISSUE THREAD

**Issue by RyoYuki** [mayfes-ar/game#12]
- 一画面に最大n個。
  *\* ボスのHPに応じて個数を変える。
  *\* 初期位置と初期速度も管理

**Comment by robonich** [comment]
### 検討
- fireball を作るときはfireball manager を通して作るのか？それとも作ったfireballを fireballに渡せばいいのか？
- fireballが消えるときは、disappearフラグを立てるのではなく、manager の list から消す？

**Comment by robonich** [comment]
Fireball managerではなくて普通に breakout_components に　fireball_list を追加する

**Comment by robonich** [comment]
- [x] `FireballKind` を追加
  - `Enemy~` だと、`Block` の影響を受けないで向かってくる
    - `Strong` ならば 強化された`Ship` か、 `Pot` じゃないと防げない。
    - `Weak` なら普通に `Ship` で跳ね返せる
    - 跳ね返されたものは強さは保ったまま `Player~` となる。
  - `Player~` は、 `Block` と普通にぶつかる。
    - `Strong` ならば 強い `Block` も一撃で壊せる。ボスにも少し大きいダメージ。
    - `Weak` は `Block.m_life` を `1` だけ減らす。ボスには `1` ダメージ。

→ #15 に委譲
