### ISSUE TITLE
BGMを探す！

### ISSUE THREAD

**Issue by robonich** [mayfes-ar/game#22]
- [x] fireball が跳ね返るときの音
- [x] ボスにfireballがあたったときのうめき声
- [x] 家が燃える音
- [ ] 姫の悲鳴
- [x] ブロックが壊れる音
- [ ] のどかな場面用のBGM
- [ ] 少し緊張感がある場面用のBGM
- [ ] 結構緊迫感がある場面用のBGM
- [x] 爆弾が爆発する音
- [x] なんか体力が回復しそうな音
- [x] 無敵状態の音

**Comment by ssww0819** [comment]
> 爆弾が爆発する音
> http://www.kurage-kosho.info/battle.html　     　爆発破壊系　小爆発02
> 
> 家が燃える音
> http://taira-komori.jpn.org/magic01.html         火　炎1
> http://taira-komori.jpn.org/quick/quick.cgi?mode=find&word=%89%CE%8D%D0   explosion
> 
> なんか体力が回復しそうな音
> http://www.kurage-kosho.info/battle.html                回復01
> 
> ボスにfireballがあたったときのうめき声
> http://www.kurage-kosho.info/nature.html                唸り声02
> 
> fireball が跳ね返るときの音
> http://www.kurage-kosho.info/others.html             木魚01
> http://soundeffect-lab.info/sound/various/various3.html          サッカーボールが跳ねる1
> 
> ブロックが壊れる音
> http://www.kurage-kosho.info/battle.html                   攻撃03
> 
> 無敵状態の音
> http://soundeffect-lab.info/sound/battle/                    オーラ2

**Comment by ssww0819** [comment]
姫の悲鳴とBGM以外は探しました。

悲鳴はいろいろ聞きましたがやはり微妙でした、BGMはわたしあんまりそのゲームについて詳しくないし、どういう音楽がふさわしいのかイメージがないです

**Comment by robonich** [comment]
ありがとう！助かりました
