### ISSUE TITLE
衝突判定を実装

### ISSUE THREAD

**Issue by RyoYuki** [mayfes-ar/game#4]

**Comment by robonich** [comment]
`fireball` のスピードが早くなると 1 frameで進むピクセルが増えて壁にはまりやすくなる。だから `isOnline` メソッドに 速度を与えられるようにしたい。そして速度が速くなればなるほど衝突判定を緩めれば解決できると思われる。やってもよい？

**Comment by RyoYuki** [comment]
お願いします

**Comment by robonich** [comment]
了解

**Comment by robonich** [comment]
ちょっと改良した
[このコミット](https://github.com/mayfes-ar/game/commit/c3e38199fa35230cd7a894519f9b36ef9fbd9612)

**Comment by robonich** [comment]
- [x] 衝突後の速度を船の速度も考慮したものにする。

**Comment by robonich** [comment]
- [x] 入射角度が浅いもののときは少し角度を大きくして返す
