### ISSUE TITLE
ポットクラスを作りゲームに組み込む

### ISSUE THREAD

**Issue by robonich** [mayfes-ar/game#6]

**Comment by robonich** [comment]
一度遊んでみてなんか疑問に思ったら教えてください。
`？` のマーカーを使えば `pot` を出現させることができます。

**Comment by RyoYuki** [comment]
確認しました

**Comment by robonich** [comment]
~~pot のマーカーをship のマーカーと同じものにして、下に上げたときに pot を出現させて、 上にしたら打ち出すというものにする。　15 frames ごとに前位置を記録~~
- [x] マーカーの前後を利用した絶対位置によって制御することにした
