### ISSUE TITLE
Itemクラスを作る

### ISSUE THREAD

**Issue by robonich** [mayfes-ar/game#7]
ブロックを崩したときにそこから `Item` が落ちてくる感じ

**Comment by RyoYuki** [comment]
Observer, Subjectパターンで実装すればよさそう

**Comment by RyoYuki** [comment]
<del>今日、時間があるからやります</del>

**Comment by RyoYuki** [comment]
お願いします

**Comment by robonich** [comment]
やります

**Comment by robonich** [comment]
実装した。
アイテムを追加したい場合は
`ItemKind` にそれを記述して、 `ItemReceiver` class を継承しているクラスの `applyItem` に対応する効果を書き込む

**Comment by robonich** [comment]
~~\- [ ] 無敵Itemを作る~~
~~\- [ ] `Pot` 回復 Item を作る~~
~~\- [ ] 時間回復Itemを作る~~
→ #17 に移譲
